/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MJ1fjGAcgY1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext, CarouselIndicators } from "@/components/ui/carousel"
import { Button } from "@/components/ui/button"

export function Carousel() {
  return (
    <div className="w-full max-w-4xl mx-auto">
      <Carousel className="rounded-lg overflow-hidden">
        <CarouselContent>
          <CarouselItem>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="relative aspect-video overflow-hidden">
                <img
                  src="/placeholder.svg"
                  alt="Slide 1 Image"
                  width={800}
                  height={450}
                  className="object-cover w-full h-full"
                  style={{ aspectRatio: "800/450", objectFit: "cover" }}
                />
              </div>
              <div className="flex flex-col justify-center gap-4 p-6 md:p-8">
                <h3 className="text-2xl font-bold">Introducing Our New Product</h3>
                <p className="text-muted-foreground">
                  Discover the latest innovation in our product line, designed to revolutionize the way you approach
                  your daily tasks.
                </p>
                <div className="flex items-center gap-2">
                  <Button variant="outline">Learn More</Button>
                  <Button>Buy Now</Button>
                </div>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="relative aspect-video overflow-hidden">
                <img
                  src="/placeholder.svg"
                  alt="Slide 2 Image"
                  width={800}
                  height={450}
                  className="object-cover w-full h-full"
                  style={{ aspectRatio: "800/450", objectFit: "cover" }}
                />
              </div>
              <div className="flex flex-col justify-center gap-4 p-6 md:p-8">
                <h3 className="text-2xl font-bold">Elevate Your Experience</h3>
                <p className="text-muted-foreground">
                  Upgrade your daily routine with our latest product, designed to enhance your productivity and bring
                  more joy to your life.
                </p>
                <div className="flex items-center gap-2">
                  <Button variant="outline">Learn More</Button>
                  <Button>Buy Now</Button>
                </div>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="relative aspect-video overflow-hidden">
                <img
                  src="/placeholder.svg"
                  alt="Slide 3 Image"
                  width={800}
                  height={450}
                  className="object-cover w-full h-full"
                  style={{ aspectRatio: "800/450", objectFit: "cover" }}
                />
              </div>
              <div className="flex flex-col justify-center gap-4 p-6 md:p-8">
                <h3 className="text-2xl font-bold">Redefine Your Routine</h3>
                <p className="text-muted-foreground">
                  Experience the difference with our latest product, designed to streamline your daily tasks and help
                  you achieve more.
                </p>
                <div className="flex items-center gap-2">
                  <Button variant="outline">Learn More</Button>
                  <Button>Buy Now</Button>
                </div>
              </div>
            </div>
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious className="absolute left-4 top-1/2 -translate-y-1/2 z-10">
          <ChevronLeftIcon className="w-6 h-6" />
        </CarouselPrevious>
        <CarouselNext className="absolute right-4 top-1/2 -translate-y-1/2 z-10">
          <ChevronRightIcon className="w-6 h-6" />
        </CarouselNext>
        <div className="absolute bottom-4 left-1/2 -translate-x-1/2 z-10" />
      </Carousel>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
