/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fN3XWls1aMh
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function Project() {
  return (
    <div className="flex flex-col min-h-dvh">
      <main className="flex-1">
        <section id="projects" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Projek Kami</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">Berikut beberapa proyek yang pernah kami kerjakan.</p>
              </div>
            </div>
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <div className="relative overflow-hidden rounded-lg group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                  <span className="sr-only">View Project</span>
                </Link>
                <img src="/deduke.png" alt="Project 1" width={400} height={300} className="object-cover w-full h-60" style={{ aspectRatio: "400/300", objectFit: "cover" }} />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-semibold md:text-xl">De Duke</h3>
                  <p className="text-sm text-muted-foreground">A web application for managing tasks and projects.</p>
                </div>
              </div>
              <div className="relative overflow-hidden rounded-lg group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                  <span className="sr-only">View Project</span>
                </Link>
                <img src="/placeholder.svg" alt="Project 2" width={400} height={300} className="object-cover w-full h-60" style={{ aspectRatio: "400/300", objectFit: "cover" }} />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-semibold md:text-xl">Project 2</h3>
                  <p className="text-sm text-muted-foreground">A mobile app for tracking fitness activities.</p>
                </div>
              </div>
              <div className="relative overflow-hidden rounded-lg group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                  <span className="sr-only">View Project</span>
                </Link>
                <img src="/placeholder.svg" alt="Project 3" width={400} height={300} className="object-cover w-full h-60" style={{ aspectRatio: "400/300", objectFit: "cover" }} />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-semibold md:text-xl">Project 3</h3>
                  <p className="text-sm text-muted-foreground">A web-based e-commerce platform.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function MountainIcon(props) {
  return (
    <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
