/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HdYoLpWwxer
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";

export function Testimoni() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center justify-center gap-10 px-4 text-center md:px-6">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-blue-500">What Our Customers Say</h2>
          <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">Hear from our satisfied customers about their experience with our products and services.</p>
        </div>
        <div className="grid w-full grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 xl:gap-8">
          <div className="flex flex-col items-start gap-4 rounded-lg bg-background p-6 shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
            <div className="flex items-center gap-4">
              <Avatar className="h-12 w-12 border">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Sarah Johnson</h3>
                <p className="text-sm text-muted-foreground">CEO, Acme Inc.</p>
              </div>
            </div>
            <blockquote className="text-lg leading-relaxed">"The customer service I received was exceptional. The support team went above and beyond to address my concerns."</blockquote>
          </div>
          <div className="flex flex-col items-start gap-4 rounded-lg bg-background p-6 shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
            <div className="flex items-center gap-4">
              <Avatar className="h-12 w-12 border">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Alex Smith</h3>
                <p className="text-sm text-muted-foreground">CTO, Globex Inc.</p>
              </div>
            </div>
            <blockquote className="text-lg leading-relaxed">
              "I recently purchased the SparkleShine Home Cleaning Robot, and it has been a game-changer in my life. I used to spend hours every weekend cleaning my house, but now I can simply turn on this little robot and let it do the
              work."
            </blockquote>
          </div>
          <div className="flex flex-col items-start gap-4 rounded-lg bg-background p-6 shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
            <div className="flex items-center gap-4">
              <Avatar className="h-12 w-12 border">
                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Emily Parker</h3>
                <p className="text-sm text-muted-foreground">Head of Design, Acme Inc.</p>
              </div>
            </div>
            <blockquote className="text-lg leading-relaxed">
              "The battery life is impressive, lasting me for long-haul flights without any issues. They are comfortable to wear for extended periods, and I appreciate the sleek design. Worth every penny, and I'd recommend these headphones
              to anyone who values high-quality audio and peace and quiet."
            </blockquote>
          </div>
        </div>
      </div>
    </section>
  );
}
